import type { AppProps } from 'next/app';
import { Metadata } from 'next';
import '../app/globals.css';

import { UserProvider } from '../context/userContext';

export const metadata: Metadata = {
    title: "Digital Protein | 2025",
    description: "Generated by create next app",
};

function MyApp({ Component, pageProps }: AppProps) {
    return (
        <>
            <UserProvider>
                <Component {...pageProps} />
            </UserProvider>
        </>
    )
}

export default MyApp
